on: [push, pull_request]

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Run Rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Run Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
  doc:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-default-features --no-deps
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: "1"
      RUSTFLAGS: "-D dead_code -D unused-variables -D unused"
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features
